final paymentFormProperties = {
  'channel': 'mobile',
  'countable': true,
  'securityToken': null,
  'merchant': '456879852',
  'purchaseNumber': null,
  'amount': null,
  'endPointURL': 'https://apisandbox.vnforappstest.com/',
  'certificateHost': 'apisandbox.vnforappstest.com',
  'certificatePin': 'sha256/lmxiL6uol7hb4UwDxtk2qbF2lBnJc7zqZRT6sFfYWEE=',
  'registerName': null,
  'registerLastname': null,
  'registerEmail': null,
  'userToken': null,
};
